// automatically generated by the FlatBuffers compiler, do not modify

package service.response;

public final class StatusCode {
  private StatusCode() {
  }

  public static final short NONE = 0;
  public static final short SYSTEM_OK = 200;
  public static final short SYSTEM_NOT_MODIFIED = 303;
  public static final short SYSTEM_BAD_REQUEST = 400;
  public static final short SYSTEM_UNAUTHORIZED = 401;
  public static final short SYSTEM_NOT_FOUND = 404;
  public static final short SYSTEM_TOKEN_EXPIRE = 406;
  public static final short SYSTEM_RESET_DEVICE = 409;
  public static final short SYSTEM_USER_INVALID = 410;
  public static final short SYSTEM_PARAM_INVALID = 412;
  public static final short SYSTEM_SERVER_ERROR = 500;
  public static final short SYSTEM_SERVER_MAINTAIN = 503;
  public static final short SYSTEM_SERVER_DOWN_TIME = 521;
}